# Maps keyboard/mouse chords to UI events
# See https://github.com/tcolar/goed/blob/master/event/event_type.go
#
# Edit in ~/.goed/bindings.toml
# - MC1 stands for Mouse Click button 1 // 1 is left, 2 middle, 4 right
# - MD1 stands for Mouse Drag button 1
# - MDC1 stand for Mouse Double Click button 1
"MC1" = "set_cursor"
"MC4" = "open_in_new_view"
"MC8" = "scroll_up"
"MC16" = "scroll_down"
"MD1" = "select_mouse"
"MDC1" = "select_word"
"alt+down_arrow" = "nav_down"
"alt+left_arrow" = "nav_left"
"alt+right_arrow" = "nav_right"
"alt+up_arrow" = "nav_up"
"backspace" = "backspace"
"ctrl+a" = "home"
"ctrl+b" = "select_all"
"ctrl+c" = "copy"
"ctrl+e" = "end"
"ctrl+h" = "move_left"
"ctrl+j" = "move_right"
"ctrl+k" = "move_up"
"ctrl+l" = "move_down"
"ctrl+n" = "open_in_new_view"
"ctrl+o" = "open_in_same_view"
"ctrl+q" = "quit"
"ctrl+r" = "reload"
"ctrl+s" = "save"
"ctrl+t" = "open_term"
"ctrl+u" = "delete_home"
"ctrl+v" = "paste"
"ctrl+w" = "close_window"
"ctrl+x" = "cut"
"ctrl+y" = "redo"
"ctrl+z" = "undo"
"delete" = "delete"
"down_arrow" = "move_down"
"end" = "end"
"enter" = "enter"
"escape" = "toggle_cmd_bar"
"home" = "home"
"left_arrow" = "move_left"
"next" = "page_down"
"prior" = "page_up"
"return" = "enter"
"right_arrow" = "move_right"
"shift+down_arrow" = "select_down"
"shift+end" = "select_end"
"shift+home" = "select_home"
"shift+left_arrow" = "select_left"
"shift+next" = "select_page_down"
"shift+prior" = "select_page_up"
"shift+right_arrow" = "select_right"
"shift+up_arrow" = "select_up"
"super+down_arrow" = "nav_down"
"super+left_arrow" = "nav_left"
"super+right_arrow" = "nav_right"
"super+up_arrow" = "nav_up"
"tab" = "tab"
"up_arrow" = "move_up"

